- type: job
  id: USPDOfficer
  name: job-name-uspd-officer
  description: job-description-uspd-officer
  playTimeTracker: JobUSPDOfficer
  weight: 70
  startingGear: USPDOfficerGear
  alwaysUseSpawner: true
  icon: "JobIconINDSecurity"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: ChatRank
      rank: BF-rank-policeofficer
    - type: NpcFactionMember
      factions:
      - USPD
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - NATOCommon
  - Security
  - Brig
  - Command
  - Medical
  - Cargo
  - Engineering
  - Research

- type: startingGear
  id: USPDOfficerGear
  equipment:
    id: USPDOfficerPDA
    ears: ClothingHeadsetAltWPS
    belt: ClothingBeltStationSecurityFilled
    jumpsuit: ClothingUniformJumpsuitUSPD
    outerClothing: ClothingOuterArmorWebVestSec
    shoes: ClothingShoesBootsJackFilled
#    back: ClothingBackpackSecurity
    pocket1: WeaponPistolATGlock17
    pocket2: PouchFirstAidFilled
  storage:
    back:
    - Tourniquet
    - Zipties
