########################## USA

- type: playTimeTracker
  id: WA68_RolePactUssrArtilleryCannoneerTime

- type: playTimeTracker
  id: WA68_RolePactUssrArtilleryChiefTime


- type: playTimeTracker
  id: WA68_RoleNatoUsaArmyReserveTime

- type: playTimeTracker
  id: WA68_RoleNatoUsaArmyInfantryTime

- type: playTimeTracker
  id: WA68_RoleNatoUsaArmySquadLeaderTime

- type: playTimeTracker
  id: WA68_RoleNatoUsaArmyPlatoonleaderTime

- type: playTimeTracker
  id: WA68_RoleNatoUsaArmyCompanyleaderTime

- type: playTimeTracker
  id: WA68_RoleNatoUsaMarineReserveTime

- type: playTimeTracker
  id: WA68_RoleNatoUsaMarineInfantryTime

- type: playTimeTracker
  id: WA68_RoleNatoUsaMarineSquadLeaderTime

- type: playTimeTracker
  id: WA68_RoleNatoUsaMarinePlatoonleaderTime

- type: playTimeTracker
  id: WA68_RoleNatoUsaMarineCompanyleaderTime

########################## USSR

- type: playTimeTracker
  id: WA68_RoleNatoUsaArtilleryCannoneerTime

- type: playTimeTracker
  id: WA68_RoleNatoUsaArtilleryChiefTime

- type: playTimeTracker
  id: WA68_RolePactUssrArmyReserveTime

- type: playTimeTracker
  id: WA68_RolePactUssrArmyInfantryTime

- type: playTimeTracker
  id: WA68_RolePactUssrArmySquadLeaderTime

- type: playTimeTracker
  id: WA68_RolePactUssrArmyPlatoonleaderTime

- type: playTimeTracker
  id: WA68_RolePactUssrArmyCompanyleaderTime

- type: playTimeTracker
  id: WA68_RolePactUssrAirborneReserveTime

- type: playTimeTracker
  id: WA68_RolePactUssrAirborneInfantryTime

- type: playTimeTracker
  id: WA68_RolePactUssrAirborneSquadLeaderTime

- type: playTimeTracker
  id: WA68_RolePactUssrAirbornePlatoonleaderTime

- type: playTimeTracker
  id: WA68_RolePactUssrAirborneCompanyleaderTime

- type: playTimeTracker
  id: WA68_RolePactUssrMarineReserveTime

- type: playTimeTracker
  id: WA68_RolePactUssrMarineInfantryTime

- type: playTimeTracker
  id: WA68_RolePactUssrMarineSquadLeaderTime

- type: playTimeTracker
  id: WA68_RolePactUssrMarinePlatoonleaderTime

- type: playTimeTracker
  id: WA68_RolePactUssrMarineCompanyleaderTime