- type: job
  id: NGLieutenant
  name: job-name-ng-lieutenant
  description: job-description-ng-lieutenant
  playTimeTracker: JobNGLieutenant
  weight: 79
  startingGear: NGLieutenantGear
  alwaysUseSpawner: true
  icon: "JobIconNATOAllyCaptain"
  requireAdminNotify: true
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    - Esperanto
    languagesUnderstood:
    - English
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
    - type: ChatRank
      rank: BF-rank-lieutenant
    - type: CMVendorUser
      id: ARNGLieutenant
      points: 4
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOCommand
  - NATOMaintenance
  - NATOSoldier
  - NATOArmory
  - NATOFunds
  - NATOCrew
  - NATOCaptain

- type: startingGear
  id: NGLieutenantGear
  equipment:
    id: NGLieutenantPDA
    ears: ClothingHeadsetAltUSCommand
    belt: ClothingBeltMilitaryWebbingUSFilledSTANAGTracerRed
    jumpsuit: ClothingUniformJumpsuitCamoUSM81Urban
    head: ClothingHeadHatHelmetUSUrban
    outerClothing: ClothingOuterArmorPlateCarrierIOTV
    shoes: ClothingShoesBootsJackFilledUSMC
    suitstorage: WeaponRifleUSCAR15
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledUSARifleman
    rightarmband: ClothingArmbandThighHolsterFilledUS
  storage:
    back:
    - ArmorPlateMediumPackaged
    - BoxPinpointerUniversalNATO
    - ClothingMaskGasM40
    - FlashlightMilitaryUS
    - MagazinePistolM9
    - MagazinePistolM9
    - Whistle
    - Tourniquet
    - Zipties
    - CMVendARNGWarVendorLieutenantTablet
