- type: job
  id: NGMedic
  name: job-name-ng-medic
  description: job-description-ng-medic
  playTimeTracker: JobNGMedic
  weight: 75
  startingGear: NGMedicGear
  alwaysUseSpawner: true
  icon: "JobIconNATOAllyMedic"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
    - type: ChatRank
      rank: BF-rank-us-lancecorporal
    - type: SurgerySpeedModifier
      SpeedModifier: 1.65
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - Medical
  - NATOCommon
  - NATOMaintenance
  - NATOMedical
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: NGMedicGear
  equipment:
    id: NGMedicPDA
    ears: ClothingHeadsetAltUS
    belt: ClothingBeltMedicalEMTFilledBF14 # ClothingBeltMilitaryWebbingUSFilledMP5
    jumpsuit: ClothingUniformJumpsuitCamoUSM81Urban
    head: ClothingHeadHatHelmetUSUrban
    eyes: ClothingEyesHudMedicalBF
    outerClothing: ClothingOuterArmorPlateCarrierIOTV
    shoes: ClothingShoesBootsJackFilledUSMC
    gloves: ClothingHandsGlovesLatex
#    back: ClothingBackpackRucksackTan
    suitstorage: WeaponRifleUSM4
    pocket1: PouchMagsLargeFilledSTANAG
    pocket2: PouchGrenadesFilledUSMCScout
  inhand:
    - PaperWrittenManualCombatMedic
  storage:
    back:
    - SupplyBoxMedicalFilled
    - DefibrillatorCompactBF
    - ClothingMaskGasM40
    - FlashlightMilitaryUS
    - Tourniquet
    - Zipties
    - BiofoamCanisterRedDARPA
