- type: job
  id: USMCRecon
  name: job-name-usmc-recon
  description: job-description-usmc-recon
  playTimeTracker: JobUSMCRecon
  weight: 74
  startingGear: USMCReconGear
  alwaysUseSpawner: true
  icon: "JobIconNATORecon"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
    - type: ChatRank
      rank: BF-rank-privatefirstclass
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOMaintenance
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: USMCReconGear
  equipment:
    id: USMCReconPDA
    ears: ClothingHeadsetAltUS
    belt: ClothingBeltMilitaryWebbingUSFilledSTANAG
    jumpsuit: ClothingUniformJumpsuitCamoUS
    head: ClothingHeadHatHelmetUS
    helmetattachment: ClothingHelmetAttachmentNVGsBasicNATO
    outerClothing: ClothingOuterArmorPlateCarrierTan
    shoes: ClothingShoesBootsJackFilledUSMC
    suitstorage: WeaponRifleUSM4A1SUPP
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledUSMCScout
  storage:
    back:
    - ClothingMaskGasM40
    - FlashlightMilitaryUS
    - Rangefinder
    - Tourniquet
    - Zipties
