using System.Numerics;
using Content.Shared.Explosion;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Log;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;
using static Robust.Client.UserInterface.Controls.OptionButton;
using Content.Shared._VXS14.Mortar;
using Content.Client.Eui;

namespace Content.Client._VXS14.Mortar;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class MortarWindow : DefaultWindow
{
    [Dependency] private readonly IClientConsoleHost _conHost = default!;
    [Dependency] private readonly IMapManager _mapManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly SharedTransformSystem _transform = default!;

    private MortarEui? _eui;
    private MapId _mapData = new();
    /// <summary>
    ///     Used to prevent unnecessary preview updates when setting fields (e.g., updating position)..
    /// </summary>
    private bool _pausePreview;

    // Default ranges in case configuration isn't received
    private float _minOffsetX = -50f;
    private float _maxOffsetX = 50f;
    private float _minOffsetY = -50f;
    private float _maxOffsetY = 50f;

    public MortarWindow()
    {
        Logger.InfoS("mortar-window", "Attempting to load XAML for MortarWindow");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _transform = _entMan.System<TransformSystem>();
    }

    public void SetEui(MortarEui eui)
    {
        _eui = eui;

        Recentre.OnPressed += (_) => ResetOffsets();
        Spawn.OnPressed += SubmitButtonOnOnPressed;
    }

    public void SetMortarConfig(float minOffsetX, float maxOffsetX, float minOffsetY, float maxOffsetY)
    {
        _minOffsetX = minOffsetX;
        _maxOffsetX = maxOffsetX;
        _minOffsetY = minOffsetY;
        _maxOffsetY = maxOffsetY;
    }

    protected override void EnteredTree()
    {
        ResetOffsets();
    }

    /// <summary>
    ///     Reset the offset values to a safe default.
    /// </summary>
    private void ResetOffsets()
    {
        _pausePreview = true;
        OffsetX.Text = "5";
        OffsetY.Text = "0";
        _pausePreview = false;
    }

    private bool TryGetOffsets(out float offsetX, out float offsetY)
    {
        offsetX = 0f;
        offsetY = 0f;

        if (!float.TryParse(OffsetX.Text, System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out offsetX))
            return false;

        if (!float.TryParse(OffsetY.Text, System.Globalization.NumberStyles.Float,
                System.Globalization.CultureInfo.InvariantCulture, out offsetY))
            return false;

        return true;
    }

    private void SubmitButtonOnOnPressed(ButtonEventArgs args)
    {
        if (!TryGetOffsets(out var offsetX, out var offsetY))
            return;

        _eui?.SendCords(new Vector2(offsetX, offsetY));
    }
}

