- type: startingGear
  id: BF14DeathmatchGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorWebVestSecEmpty
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackButtpackSurplus
    neck: FlashlightMilitaryUS
    suitstorage: WeaponRifleUSM4
    pocket1: WeaponPistolILDeagleSilver
    pocket2: PouchFirstAidFilled

- type: startingGear
  id: BF14GoonGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCombatSuitDigitalBlack
    ears: ClothingHeadsetGrey
    balaclava: ClothingBalaclavaSkiMaskMouthBlack
    outerClothing: ClothingOuterArmorWebVestSec
    belt: ClothingBeltStationSecurityFilled
    shoes: ClothingShoesBootsJackFilled
    pocket2: PouchFirstAidFilled

- type: startingGear
  id: BF14TDMGearBlue
  equipment:
    id: USMCRiflemanIDCard
    jumpsuit: ClothingUniformJumpsuitMilitaryColorBlueTDM
    head: ClothingHeadHatHelmetSecurityBF14
    balaclava: ClothingBalaclavaMilitary
    ears: ClothingHeadsetAltUS
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorPCVRecharging
    belt: ClothingBeltAssault
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackButtpackSurplus
    neck: ClothingNeckIFFBlue
    leftarmband: FlashlightMilitaryUS
    suitstorage: WeaponRifleDEG36K
    pocket1: WeaponPistolILDeagleSilver
    pocket2: PouchFirstAidFilled
  storage:
    back:
    - BiofoamCanister
    - CrowbarRed
    - DefensiveGrenadeUSM67
    - Tourniquet
    belt:
    - MagazinePistolDeagle
    - MagazinePistolDeagle
    - MagazineRifleG36
    - MagazineRifleG36
    - MagazineRifleG36
    - MagazineRifleG36
    - MagazineRifleG36

- type: startingGear
  id: BF14TDMGearRed
  equipment:
    id: VDVRiflemanIDCard
    jumpsuit: ClothingUniformJumpsuitMilitaryColorRedTDM
    head: ClothingHeadHatHelmetSecurityBF14
    balaclava: ClothingBalaclavaMilitary
    ears: ClothingHeadsetAltRU
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorPCVRecharging
    belt: ClothingBeltAssault
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackButtpackSurplus
    neck: ClothingNeckIFFRed
    leftarmband: FlashlightMilitaryAlt
    suitstorage: WeaponRifleRUAK74M
    pocket1: WeaponPistolILDeagleSilver
    pocket2: PouchFirstAidFilled
  storage:
    back:
    - BiofoamCanisterRed
    - CrowbarRed
    - DefensiveGrenadeUSM67
    - Tourniquet
    belt:
    - MagazinePistolDeagle
    - MagazinePistolDeagle
    - MagazineRifleAK74Black
    - MagazineRifleAK74Black
    - MagazineRifleAK74Black
    - MagazineRifleAK74Black
    - MagazineRifleAK74Black
