- type: department
  id: TDMBlue
  name: TDM (Blue)
  description: lorum ipsum
  color: "#203564"
  weight: 6
  roles:
  - TDMBlue
  - TDMBluePointman
  - TDMBlueMarksman

- type: job
  id: TDMBlue
  name: Blue Goon
  description: Shoot reds.
  playTimeTracker: JobTDMBlue
  displayWeight: 4
  startingGear: BF14TDMGearBlue
  alwaysUseSpawner: true
  icon: "JobIconNATORifleman"
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Blue
    - Esperanto
    languagesUnderstood:
    - Blue
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
  access:
  - Maintenance

- type: job
  id: TDMBluePointman
  name: Blue Pointman
  description: Push reds.
  playTimeTracker: JobTDMBluePointman
  displayWeight: 5
  startingGear: BF14TDMGearBluePointman
  alwaysUseSpawner: true
  icon: "JobIconNATOSpecialForces"
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Blue
    - Esperanto
    languagesUnderstood:
    - Blue
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
  access:
  - Maintenance

- type: job
  id: TDMBlueMarksman
  name: Blue Marksman
  description: Snipe reds.
  playTimeTracker: JobTDMBlueMarksman
  displayWeight: 6
  startingGear: BF14TDMGearBlueMarksman
  alwaysUseSpawner: true
  icon: "JobIconNATORecon"
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Blue
    - Esperanto
    languagesUnderstood:
    - Blue
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
  access:
  - Maintenance

- type: department
  id: TDMRed
  name: TDM (Red)
  description: lorum ipsum
  color: "#a02829"
  weight: 7
  roles:
  - TDMRed
  - TDMRedPointman
  - TDMRedMarksman

- type: job
  id: TDMRed
  name: Red Goon
  description: Shoot blues.
  playTimeTracker: JobTDMRed
  displayWeight: 1
  startingGear: BF14TDMGearRed
  alwaysUseSpawner: true
  icon: "JobIconPACTRifleman"
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Red
    - Esperanto
    languagesUnderstood:
    - Red
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - VDV
  access:
  - Maintenance

- type: job
  id: TDMRedPointman
  name: Red Pointman
  description: Push blues.
  playTimeTracker: JobTDMRedPointman
  displayWeight: 2
  startingGear: BF14TDMGearRedPointman
  alwaysUseSpawner: true
  icon: "JobIconPACTSpecialForces"
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Red
    - Esperanto
    languagesUnderstood:
    - Red
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - VDV
  access:
  - Maintenance

- type: job
  id: TDMRedMarksman
  name: Red Marksman
  description: Snipe blues.
  playTimeTracker: JobTDMRedMarksman
  displayWeight: 3
  startingGear: BF14TDMGearRedMarksman
  alwaysUseSpawner: true
  icon: "JobIconPACTRecon"
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Red
    - Esperanto
    languagesUnderstood:
    - Red
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - VDV
  access:
  - Maintenance