- type: job
  id: NationalistUA # Change it to CivilianUANationalist later
  name: Nationalist
  description: job-description-ind-civilian
  playTimeTracker: JobNationalistUA
  displayWeight: 12
#  startingGear: PassengerGear
  alwaysUseSpawner: true
  icon: "JobIconUA"
#  supervisors: job-supervisors-everyone
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Ukrainian
    languagesUnderstood:
    - Ukrainian
    - Russian
  access:
  - Maintenance
