- type: job
  id: WA68_RoleNatoUsaArmyReserve
  name: US Army reservist
  description: When your predecessors fail you get sent into the meatgrinder.
  playTimeTracker: WA68_RoleNatoUsaArmyReserveTime
  weight: 77
  startingGear: WA68_RoleNatoUsaArmyReserveGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconNatoReserve"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Nato
      - WA68_Usa
    - type: ChatRank
      rank: Pvt.
  requirements:
    - !type:SexRequirement
    sex: Male

- type: startingGear
  id: WA68_RoleNatoUsaArmyReserveGear
  equipment:
    id: WA68_ClothingDogtagUsaArmyReserve
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUsaOG107
    belt: WA68_ClothingBeltMilitaryWebbingUsaM1967FilledM1420Rnd
    head: WA68_ClothingHeadHatUsaPatrolCap
    back: WA68_ClothingBackpackUsaM1961
    suitstorage: WA68_WeaponUsaM14
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_M26A1_M18
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledM17

- type: job
  id: WA68_RoleNatoUsaArmyRifleman
  name: US Army infantryman
  description: Be the cannon fodder for United States of America. Run off alone into combat thinking youre "him" and die to a sniper
  playTimeTracker: WA68_RoleNatoUsaArmyRiflemanTime
  weight: 77
  startingGear: WA68_RoleNatoUsaArmyRiflemanGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconNatoRifleman"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Nato
      - WA68_Usa
    - type: ChatRank
      rank: Pfc.
  requirements:
    - !type:SexRequirement
    sex: Male

- type: startingGear
  id: WA68_RoleNatoUsaArmyRiflemanGear
  equipment:
    id: WA68_ClothingDogtagUsaArmyRifleman
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUsaOG107
    belt: WA68_ClothingBeltMilitaryWebbingUsaM1967FilledSTANAG30Rnd
    head: WA68_ClothingHeadHelmetUsaM1
    outerClothing: WA68_ClothingOuterArmorUsaM69
    back: WA68_ClothingBackpackUsaM1961
    suitstorage: WA68_WeaponUsaM16A1
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_M67_M18
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledM17

- type: job
  id: WA68_RoleNatoUsaArmySquadLeader
  name: US Army squad leader
  description: Try to manage you squad of meatshields. Get blamed for everything.
  playTimeTracker: WA68_RoleNatoUsaArmySquadLeaderTime
  weight: 77
  startingGear: WA68_RoleNatoUsaArmySquadLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconNatoSquadLeader"
  requireAdminNotify: false
  supervisors: Platoon commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Nato
      - WA68_Usa
    - type: ChatRank
      rank: Sgt.
  requirements:
    - !type:SexRequirement
    sex: Male

- type: startingGear
  id: WA68_RoleNatoUsaArmySquadLeaderGear
  equipment:
    id: WA68_ClothingDogtagUsaArmySquadLeader
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUsaOG107
    belt: WA68_ClothingBeltMilitaryWebbingUsaM1967FilledSTANAG30Rnd
    head: WA68_ClothingHeadHelmetUsaM1
    outerClothing: WA68_ClothingOuterArmorUsaM69
    back: WA68_ClothingBackpackRadioUsaANPRC77
    suitstorage: WA68_WeaponUsaM16A1
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_M67_M18
    rightarmband: WA68_ClothingArmbandGenericHolsterFilledM1911
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledM17
  storage:
    back:
    - WA68_Binoculars
    - WA68_MagazineM1911
    - WA68_MagazineM1911
    - WA68_MagazineM1911

- type: job
  id: WA68_RoleNatoUsaArmyPlatoonLeader
  name: US Army platoon commander
  description: Be a "mission essential" asset, yell multiple times at your "special" force to line up. Handle gear distribution if no FOB mayor shows up.
  playTimeTracker: WA68_RoleNatoUsaArmyPlatoonLeaderTime
  weight: 77
  startingGear: WA68_RoleNatoUsaArmyPlatoonLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconNatoPlatoonLeader"
  requireAdminNotify: false
  supervisors: Company commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Nato
      - WA68_Usa
    - type: ChatRank
      rank: Lt.
  requirements:
    - !type:SexRequirement
    sex: Male

- type: startingGear
  id: WA68_RoleNatoUsaArmyPlatoonLeaderGear
  equipment:
    id: WA68_ClothingDogtagUsaArmyPlatoonLeader
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUsaOG107
    belt: WA68_ClothingBeltMilitaryWebbingUsaM1967FilledSTANAG30Rnd
    head: WA68_ClothingHeadHelmetUsaM1
    outerClothing: WA68_ClothingOuterArmorUsaM69
    back: WA68_ClothingBackpackRadioUsaANPRC77
    suitstorage: WA68_WeaponUsaM16A1
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_M67_M18
    rightarmband: WA68_ClothingArmbandGenericHolsterFilledM1911
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledM17
  storage:
    back:
    - WA68_Binoculars
    - WA68_MagazineM1911
    - WA68_MagazineM1911
    - WA68_MagazineM1911