- type: job
  id: FSBRifleman
  name: job-name-fsb-rifleman
  description: job-description-fsb-rifleman
  playTimeTracker: JobFSBRifleman
  weight: 77
  startingGear: FSBRiflemanGear
  alwaysUseSpawner: true
  icon: "JobIconPACTSpecialForces"
  requireAdminNotify: false
  supervisors: job-supervisors-rugov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    - English
    - Esperanto
    languagesUnderstood:
    - Russian
    - English
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - FSB
  - !type:AddImplantSpecial
    implants: [ TrackingImplantPACTRU ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - PACTCommon
  - PACTCommand
  - PACTMaintenance
  - PACTMedical
  - PACTSoldier
  - PACTArmory

- type: startingGear
  id: FSBRiflemanGear
  equipment:
    id: FSBRiflemanPDA
    ears: ClothingHeadsetAltRU
    belt: ClothingBeltMilitaryWebbingRUFilledAK74
    jumpsuit: ClothingUniformJumpsuitRUGorka
    head: ClothingHeadHatHelmetRU6b47Alt
    helmetattachment: ClothingHelmetAttachmentNVGsBasicPACT
    balaclava: ClothingBalaclavaMilitary
    eyes: ClothingEyesGogglesGreen
    outerClothing: ClothingOuterArmorPlateCarrier6B45
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackRucksackBlack
    neck: ClothingNeckIFFtapeFSB
    suitstorage: WeaponRifleRUAK74FSB
    pocket1: PouchMedkitFilledMarsoc
    pocket2: PouchGrenadesFilledVDVRifleman
    leftarmband: ClothingArmbandSheathKnifePolymerFilledTaiga
    rightarmband: ClothingArmbandThighHolsterFilledRUSR1MP
  storage:
    back:
    - ArmorPlateMedium
    - MagazinePistolSR1MP
    - MagazinePistolSR1MP
    - CrowbarRed
    - FlashlightMilitaryAlt
    - ClothingMaskGasRussia
    - DoubleEmergencyOxygenTankFilled
    - Tourniquet
    - Zipties

- type: startingGear
  id: FSBRiflemanGearEVA
  equipment:
    id: FSBRiflemanPDA
    ears: ClothingHeadsetAltRU
    belt: ClothingBeltMilitaryWebbingRUFilledAK74
    jumpsuit: ClothingUniformJumpsuitRUGorka
    head: ClothingHeadHatSkullcrusher
    helmetattachment: ClothingHelmetAttachmentNVGsBasicPACT
    balaclava: ClothingBalaclavaMilitary
    eyes: ClothingEyesGogglesGreen
    outerClothing: ClothingOuterVoidsuitRussianCombat
    shoes: ClothingShoesBootsMagAshen
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackRucksackBlack
    neck: ClothingNeckIFFtapeFSB
    suitstorage: WeaponRifleRUAK74FSB
    pocket1: PouchMedkitFilledMarsoc
    pocket2: PouchGrenadesFilledVDVRifleman
    leftarmband: ClothingArmbandSheathKnifePolymerFilledTaiga
    rightarmband: ClothingArmbandThighHolsterFilledRUSR1MP
  storage:
    back:
    - ArmorPlateMedium
    - MagazinePistolSR1MP
    - MagazinePistolSR1MP
    - CrowbarRed
    - FlashlightMilitaryAlt
    - ClothingMaskGasRussia
    - DoubleEmergencyOxygenTankFilled
    - Tourniquet
    - Zipties
