- type: entity
  abstract: true
  id: WA68_StructureFloraBase
  suffix: WorldAblaze1968
  categories: [ HideSpawnMenu ]
  placement:
    mode: SnapgridCenter
  components:
  - type: Transform
    anchored: true
  - type: Clickable
  - type: Sprite
    drawdepth: OverMobs
  - type: SpriteFade
  - type: Physics
    bodyType: Static
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 50
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Damageable
    damageContainer: StructuralInorganic
    damageModifierSet: Wood