- type: job
  id: WA68_RolePactUssrAirborneReserve
  name: USSR Airborne reservist
  description: When your predecessors fail you get sent into the meatgrinder.
  playTimeTracker: WA68_RolePactUssrAirborneReserveTime
  weight: 77
  startingGear: WA68_RolePactUssrAirborneReserveGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactReserve"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Ryt.
  requirements:
    - !type:SexRequirement
    sex: Male

- type: startingGear
  id: WA68_RolePactUssrAirborneReserveGear
  equipment:
    id: WA68_ClothingDogtagUssrAirborneReserve
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955FilledSKS
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68__ClothingBackpackUssrRD54
    suitstorage: WA68_WeaponUssrSKS
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_F1_RDG2
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M
  storage:
    back:
    - WA68_ClothingHeadHatUssrBeretVDV

- type: job
  id: WA68_RolePactUssrAirborneRifleman
  name: USSR Airborne infantryman
  description: Be the cannon fodder for Union of Soviet Socialist Republics.
  playTimeTracker: WA68_RolePactUssrAirborneRiflemanTime
  weight: 77
  startingGear: WA68_RolePactUssrAirborneRiflemanGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactRifleman"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Ryt.
  requirements:
    - !type:SexRequirement
    sex: Male

- type: startingGear
  id: WA68_RolePactUssrAirborneRiflemanGear
  equipment:
    id: WA68_ClothingDogtagUssrAirborneRifleman
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68__ClothingBackpackUssrRD54
    suitstorage: WA68_WeaponUssrAKMS
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_RGD5_RDG2
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M
  storage:
    back:
    - WA68_ClothingHeadHatUssrBeretVDV

- type: job
  id: WA68_RolePactUssrAirborneSquadLeader
  name: USSR Airborne squad leader
  description: Try to manage you squad of meatshields. Get blamed for everything.
  playTimeTracker: WA68_RolePactUssrAirborneSquadLeaderTime
  weight: 77
  startingGear: WA68_RolePactUssrAirborneSquadLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactSquadLeader"
  requireAdminNotify: false
  supervisors: Platoon commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Szh.
  requirements:
    - !type:SexRequirement
    sex: Male

- type: startingGear
  id: WA68_RolePactUssrAirborneSquadLeaderGear
  equipment:
    id: WA68_ClothingDogtagUssrAirborneSquadLeader
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackRadioUssrR105M
    suitstorage: WA68_WeaponUssrAKMS
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_RGD5_RDG2
    rightarmband: WA68_ClothingArmbandGenericHolsterFilledPM
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M
  storage:
    back:
    - WA68_Binoculars
    - WA68_ClothingHeadHatUssrBeretVDV
    - WA68_MagazinePM
    - WA68_MagazinePM
    - WA68_MagazinePM

- type: job
  id: WA68_RolePactUssrAirbornePlatoonLeader
  name: USSR Airborne platoon commander
  description: Be a "mission essential" asset, yell multiple times at your "special" force to line up. Handle gear distribution if no FOB mayor shows up.
  playTimeTracker: WA68_RolePactUssrAirbornePlatoonLeaderTime
  weight: 77
  startingGear: WA68_RolePactUssrAirbornePlatoonLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactPlatoonLeader"
  requireAdminNotify: false
  supervisors: Company commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Lyt.
  requirements:
    - !type:SexRequirement
    sex: Male

- type: startingGear
  id: WA68_RolePactUssrAirbornePlatoonLeaderGear
  equipment:
    id: WA68_ClothingDogtagUssrAirbornePlatoonLeader
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackRadioUssrR105M
    suitstorage: WA68_WeaponUssrAKMS
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_RGD5_RDG2
    rightarmband: WA68_ClothingArmbandGenericHolsterFilledPM
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M
  storage:
    back:
    - WA68_Binoculars
    - WA68_ClothingHeadHatUssrBeretVDV
    - WA68_MagazinePM
    - WA68_MagazinePM
    - WA68_MagazinePM