- type: job
  id: WA68_RolePactUssrArmyReserve
  name: USSR Army reservist
  description: When your predecessors fail you get sent into the meatgrinder.
  playTimeTracker: WA68_RolePactUssrArmyReserveTime
  weight: 1
  startingGear: WA68_RolePactUssrArmyReserveGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactReserve"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Ryt.

- type: startingGear
  id: WA68_RolePactUssrArmyReserveGear
  equipment:
    id: WA68_ClothingDogtagUssrArmyReserve
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955FilledSKS
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackUssrVeshmeshok
    suitstorage: WA68_WeaponUssrSKS
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_F1_RDG2
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M

- type: job
  id: WA68_RolePactUssrArmyInfantry
  name: USSR Army infantryman
  description: Be the cannon fodder for Union of Soviet Socialist Republics. Run off alone into combat thinking youre ''him'' and die to a sniper.
  playTimeTracker: WA68_RolePactUssrArmyInfantryTime
  weight: 2
  startingGear: WA68_RolePactUssrArmyInfantryGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactInfantry"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Ryt.

- type: startingGear
  id: WA68_RolePactUssrArmyInfantryGear
  equipment:
    id: WA68_ClothingDogtagUssrArmyInfantry
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackUssrVeshmeshok
    suitstorage: WA68_WeaponUssrAKM
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_RGD5_RDG2
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M

- type: job
  id: WA68_RolePactUssrArmySquadLeader
  name: USSR Army squad leader
  description: Try to manage you squad of meatshields. Get blamed for everything.
  playTimeTracker: WA68_RolePactUssrArmySquadLeaderTime
  weight: 3
  startingGear: WA68_RolePactUssrArmySquadLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactLeader"
  requireAdminNotify: false
  supervisors: Platoon commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Szh.

- type: startingGear
  id: WA68_RolePactUssrArmySquadLeaderGear
  equipment:
    id: WA68_ClothingDogtagUssrArmySquadLeader
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackRadioUssrR105M
    suitstorage: WA68_WeaponUssrAKM
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_RGD5_RDG2
    rightarmband: WA68_ClothingArmbandGenericHolsterFilledPM
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M
  storage:
    back:
    - WA68_Binoculars
    - WA68_MagazinePM
    - WA68_MagazinePM
    - WA68_MagazinePM

- type: job
  id: WA68_RolePactUssrArmyPlatoonLeader
  name: USSR Army platoon commander
  description: Be a ''mission essential'' asset, yell multiple times at your ''special'' force to line up. Handle gear distribution if no FOB mayor shows up.
  playTimeTracker: WA68_RolePactUssrArmyPlatoonLeaderTime
  weight: 4
  startingGear: WA68_RolePactUssrArmyPlatoonLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactCommander"
  requireAdminNotify: false
  supervisors: Company commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Lyt.

- type: startingGear
  id: WA68_RolePactUssrArmyPlatoonLeaderGear
  equipment:
    id: WA68_ClothingDogtagUssrArmyPlatoonLeader
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackRadioUssrR105M
    suitstorage: WA68_WeaponUssrAKM
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_RGD5_RDG2
    rightarmband: WA68_ClothingArmbandGenericHolsterFilledPM
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M
  storage:
    back:
    - WA68_Binoculars
    - WA68_MagazinePM
    - WA68_MagazinePM
    - WA68_MagazinePM