- type: job
  id: WA68_RolePactUssrArmyReserve
  name: USSR Army reservist
  description: When your predecessors fail you get sent into the meatgrinder.
  playTimeTracker: WA68_RolePactUssrArmyReserveTime
  weight: 77
  startingGear: WA68_RolePactUssrArmyReserveGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactRifleman"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Ryt.

- type: job
  id: WA68_RolePactUssrArmyRifleman
  name: USSR Army infantryman
  description: Be the cannon fodder for United States of America.
  playTimeTracker: WA68_RolePactUssrArmyRiflemanTime
  weight: 77
  startingGear: WA68_RolePactUssrArmyRiflemanGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactRifleman"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Efr.

- type: job
  id: WA68_RolePactUssrArmySeniorRifleman
  name: USSR Army senior infantryman
  description: Be the cannon fodder for United States of America. Run off alone into combat thinking youre "him" and die to a sniper
  playTimeTracker: WA68_RolePactUssrArmySeniorRiflemanTime
  weight: 77
  startingGear: WA68_RolePactUssrArmyRiflemanGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactSeniorRifleman"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: MSzh.

- type: job
  id: WA68_RolePactUssrArmySquadLeader
  name: USSR Army squad leader
  description: Try to manage you squad of meatshields. Get blamed for everything.
  playTimeTracker: WA68_RolePactUssrArmySquadLeaderTime
  weight: 77
  startingGear: WA68_RolePactUssrArmyLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactSquadLeader"
  requireAdminNotify: false
  supervisors: Platoon commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Szh.

- type: job
  id: WA68_RolePactUssrArmyPlatoonLeader
  name: USSR Army platoon commander
  description: Be a "mission essential" asset, yell multiple times at your "special" force to line up. Handle gear distribution if no FOB mayor shows up.
  playTimeTracker: WA68_RolePactUssrArmyPlatoonLeaderTime
  weight: 77
  startingGear: WA68_RolePactUssrArmyLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactPlatoonLeader"
  requireAdminNotify: false
  supervisors: Company commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Lyt.