- type: job
  id: WA68_RolePactUssrArmyReserve
  name: USSR Army reservist
  description: When your predecessors fail you get sent into the meatgrinder.
  playTimeTracker: WA68_RolePactUssrArmyReserveTime
  weight: 77
  startingGear: WA68_RolePactUssrArmyReserveGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactReserve"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Ryt.
  requirements:
    - !type:SexRequirement
    sex: Male

- type: job
  id: WA68_RolePactUssrArmyRifleman
  name: USSR Army infantryman
  description: Be the cannon fodder for Union of Soviet Socialist Republics.
  playTimeTracker: WA68_RolePactUssrArmyRiflemanTime
  weight: 77
  startingGear: WA68_RolePactUssrArmyRiflemanGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactRifleman"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Efr.
  requirements:
    - !type:SexRequirement
    sex: Male

- type: startingGear
  id: WA68_RolePactUssrArmyReserveGear
  equipment:
    id: WA68_ClothingDogtagUssrArmyReserve
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955FilledSKS
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackUssrVeshmeshok
    suitstorage: WA68_WeaponUssrSKS
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_F1_RDG2
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M

- type: job
  id: WA68_RolePactUssrArmySquadLeader
  name: USSR Army squad leader
  description: Try to manage you squad of meatshields. Get blamed for everything.
  playTimeTracker: WA68_RolePactUssrArmySquadLeaderTime
  weight: 77
  startingGear: WA68_RolePactUssrArmySquadLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactSquadLeader"
  requireAdminNotify: false
  supervisors: Platoon commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Szh.
  requirements:
    - !type:SexRequirement
    sex: Male

- type: startingGear
  id: WA68_RolePactUssrArmyRiflemanGear
  equipment:
    id: WA68_ClothingDogtagUssrArmyRifleman
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackUssrVeshmeshok
    suitstorage: WA68_WeaponUssrAKM
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_RGD5_RDG2
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M

- type: startingGear
  id: WA68_RolePactUssrArmySquadLeaderGear
  equipment:
    id: WA68_ClothingDogtagUssrArmySquadLeader
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackRadioUssrR105M
    suitstorage: WA68_WeaponUssrAKM
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_RGD5_RDG2
    rightarmband: WA68_ClothingArmbandGenericHolsterFilledPM
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M
  storage:
    back:
    - WA68_Binoculars
    - WA68_MagazinePM
    - WA68_MagazinePM
    - WA68_MagazinePM

- type: job
  id: WA68_RolePactUssrArmyPlatoonLeader
  name: USSR Army platoon commander
  description: Be a "mission essential" asset, yell multiple times at your "special" force to line up. Handle gear distribution if no FOB mayor shows up.
  playTimeTracker: WA68_RolePactUssrArmyPlatoonLeaderTime
  weight: 77
  startingGear: WA68_RolePactUssrArmyPlatoonLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactPlatoonLeader"
  requireAdminNotify: false
  supervisors: Company commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Lyt.
  requirements:
    - !type:SexRequirement
    sex: Male

- type: startingGear
  id: WA68_RolePactUssrArmyPlatoonLeaderGear
  equipment:
    id: WA68_ClothingDogtagUssrArmyPlatoonLeader
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackRadioUssrR105M
    suitstorage: WA68_WeaponUssrAKM
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_RGD5_RDG2
    rightarmband: WA68_ClothingArmbandGenericHolsterFilledPM
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M
  storage:
    back:
    - WA68_Binoculars
    - WA68_MagazinePM
    - WA68_MagazinePM
    - WA68_MagazinePM