- type: job
  id: WA68_RolePactUssrFobPersonnel
  name: USSR FOB personnel
  description: Accidentaly choose this. Commit suicide, respawn as rifleman.
  playTimeTracker: WA68_RolePactUssrFobPersonnelTime
  weight: 77
  startingGear: WA68_RolePactUssrBacklineGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactFobPersonnel"
  requireAdminNotify: false
  supervisors: FOB Mayor
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Efr.

- type: job
  id: WA68_RolePactUssrFobMayor
  name: USSR FOB Mayor
  description: Manage the FOB, distribute specialized gear amongst the soilders then do nothing for 30 minutes. 
  playTimeTracker: WA68_RolePactUssrFobMayorTime
  weight: 77
  startingGear: WA68_RolePactUssrBacklineGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactFobMayor"
  requireAdminNotify: false
  supervisors: Company commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Kap.