- type: startingGear
  id: WA68_RolePactUssrBacklineGear
  equipment:
    id: WA68_ClothingDogtagUssr
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    back: WA68_ClothingBackpackUssrVeshmeshok
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955FilledPM
  storage:
    back:
    - WA68_Binoculars

- type: startingGear
  id: WA68_RolePactUssrArmyLeaderGear
  equipment:
    id: WA68_ClothingDogtagUssr
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackRadioUssrR105M
    suitstorage: WA68_WeaponUssrAKM
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_M67_M18
  storage:
    back:
    - WA68_Binoculars

- type: startingGear
  id: WA68_RolePactUssrArmyRiflemanGear
  equipment:
    id: WA68_ClothingDogtagUssr
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackUssrVeshmeshok
    suitstorage: WA68_WeaponUssrAKM
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_M67_M18

- type: startingGear
  id: WA68_RolePactUssrArmyReserveGear
  equipment:
    id: WA68_ClothingDogtagUssr
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955FilledSKS
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackUssrVeshmeshok
    suitstorage: WA68_WeaponUssrSKS
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_F1_RDG2

- type: startingGear
  id: WA68_RolePactUssrAirborneLeaderGear
  equipment:
    id: WA68_ClothingDogtagUssr
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackRadioUssrR105M
    suitstorage: WA68_WeaponUssrAKMS
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_M67_M18
  storage:
    back:
    - WA68_Binoculars
    - WA68_ClothingHeadHatUssrBeretVDV

- type: startingGear
  id: WA68_RolePactUssrAirborneRiflemanGear
  equipment:
    id: WA68_ClothingDogtagUssr
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955Filled6L10
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68__ClothingBackpackUssrRD54
    suitstorage: WA68_WeaponUssrAKMS
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_M67_M18
  storage:
    back:
    - WA68_ClothingHeadHatUssrBeretVDV

- type: startingGear
  id: WA68_RolePactUssrAirborneReserveGear
  equipment:
    id: WA68_ClothingDogtagUssr
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrM1969
    belt: WA68_ClothingBeltMilitaryWebbingUssrM1955FilledSKS
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68__ClothingBackpackUssrRD54
    suitstorage: WA68_WeaponUssrSKS
    pocket1: WA68_ClothingPouchGenericIFAKFilledGeneric
    pocket2: WA68_ClothingPouchGenericGrenadeFilled_F1_RDG2
  storage:
    back:
    - WA68_ClothingHeadHatUssrBeretVDV