- type: job
  id: WA68_RolePactUssrMarineReserve
  name: USSR Marine reservist
  description: When your predecessors fail you get sent into the meatgrinder.
  playTimeTracker: WA68_RolePactUssrMarineReserveTime
  weight: 1
  startingGear: WA68_RolePactUssrMarineReserveGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactRank0"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Ryad.

- type: startingGear
  id: WA68_RolePactUssrMarineReserveGear
  equipment:
    id: WA68_ClothingDogtagUssrMarineReserve
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrKLMK
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackUssrVeshmeshok
    suitstorage: WA68_WeaponUssrSKS
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M

- type: job
  id: WA68_RolePactUssrMarineInfantry
  name: USSR Marine infantryman
  description: Be the cannon fodder for Union of Soviet Socialist Republics. Run off alone into combat thinking youre ''him'' and die to a sniper.
  playTimeTracker: WA68_RolePactUssrMarineInfantryTime
  weight: 2
  startingGear: WA68_RolePactUssrMarineInfantryGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactRank1"
  requireAdminNotify: false
  supervisors: Squad leader
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Ryad.

- type: startingGear
  id: WA68_RolePactUssrMarineInfantryGear
  equipment:
    id: WA68_ClothingDogtagUssrMarineInfantry
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrKLMK
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackUssrVeshmeshok
    suitstorage: WA68_WeaponUssrAKMS
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M

- type: job
  id: WA68_RolePactUssrMarineSquadLeader
  name: USSR Marine squad leader
  description: Try to manage you squad of meatshields. Get blamed for everything.
  playTimeTracker: WA68_RolePactUssrMarineSquadLeaderTime
  weight: 3
  startingGear: WA68_RolePactUssrMarineSquadLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactRank3"
  requireAdminNotify: false
  supervisors: Company commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Szh.

- type: startingGear
  id: WA68_RolePactUssrMarineSquadLeaderGear
  equipment:
    id: WA68_ClothingDogtagUssrMarineSquadLeader
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrKLMK
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackRadioUssrR105M
    suitstorage: WA68_WeaponUssrAKMS
    rightarmband: WA68_ClothingArmbandGenericHolsterFilledPM
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M
  storage:
    back:
    - WA68_Binoculars
    - WA68_MagazinePM
    - WA68_MagazinePM
    - WA68_MagazinePM

- type: job
  id: WA68_RolePactUssrMarinePlatoonLeader
  name: USSR Marine platoon commander
  description: Be a ''mission essential'' asset, yell multiple times at your ''special'' force to line up.
  playTimeTracker: WA68_RolePactUssrMarinePlatoonLeaderTime
  weight: 4
  startingGear: WA68_RolePactUssrMarinePlatoonLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactRank4"
  requireAdminNotify: false
  supervisors: Company commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Lyt.

- type: startingGear
  id: WA68_RolePactUssrMarinePlatoonLeaderGear
  equipment:
    id: WA68_ClothingDogtagUssrMarinePlatoonLeader
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrKLMK
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackRadioUssrR105M
    suitstorage: WA68_WeaponUssrAKMS
    rightarmband: WA68_ClothingArmbandGenericHolsterFilledPM
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M
  storage:
    back:
    - WA68_Binoculars
    - WA68_MagazinePM
    - WA68_MagazinePM
    - WA68_MagazinePM

- type: job
  id: WA68_RolePactUssrMarineCompanyLeader
  name: USSR Marine company commander
  description: Be a ''mission essential'' asset, yell at your platoon commanders to stop dying to 1 guy, shift blame onto your subordinates.
  playTimeTracker: WA68_RolePactUssrMarineCompanyLeaderTime
  weight: 5
  startingGear: WA68_RolePactUssrMarineCompanyLeaderGear
  alwaysUseSpawner: true
  icon: "WA68_JobIconPactRank5"
  requireAdminNotify: false
  supervisors: Battalion commander
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - WA68_Pact
      - WA68_Ussr
    - type: ChatRank
      rank: Kap.

- type: startingGear
  id: WA68_RolePactUssrMarineCompanyLeaderGear
  equipment:
    id: WA68_ClothingDogtagUssrMarineCompanyLeader
    shoes: WA68_ClothingShoesBootsGeneric
    jumpsuit: WA68_ClothingUniformUssrKLMK
    head: WA68_ClothingHeadHelmetUssrSSh68
    back: WA68_ClothingBackpackRadioUssrR105M
    suitstorage: WA68_WeaponUssrAKMS
    rightarmband: WA68_ClothingArmbandGenericHolsterFilledPM
    leftarmband: WA68_ClothingArmbandGenericGasmaskFilledShM41M
  storage:
    back:
    - WA68_Binoculars
    - WA68_MagazinePM
    - WA68_MagazinePM
    - WA68_MagazinePM