- type: job
  id: BWSquadLeader
  name: job-name-bw-squadleader
  description: job-description-bw-squadleader
  playTimeTracker: JobBWSquadLeader
  weight: 68
  startingGear: BWSquadLeaderGear
  alwaysUseSpawner: true
  icon: "JobIconNATOSquadleader"
  requireAdminNotify: true
  supervisors: job-supervisors-degov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - German
    - Esperanto
    languagesUnderstood:
    - German
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - BW
    - type: ChatRank
      rank: BF-rank-sergeant
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATODE ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOCommand
  - NATOMaintenance
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: BWSquadLeaderGear
  equipment:
    id: BWSquadLeaderPDA
    ears: ClothingHeadsetAltDE
    belt: ClothingBeltMilitaryWebbingDEFilledG36TracerRed
    jumpsuit: ClothingUniformJumpsuitCamoDEFlecktarn
    head: ClothingHeadHatHelmetDEM92
    outerClothing: ClothingOuterArmorPlateCarrierMOBAST
    shoes: ClothingShoesBootsJackFilledBW
    suitstorage: WeaponRifleDEG36
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledUSMCRifleman
    rightarmband: ClothingArmbandThighHolsterFilledDEP8A1
  storage:
    back:
    - ArmorPlateMedium
    - BoxPinpointerUniversalNATO
    - ClothingMaskGasM40
    - FlashlightMilitaryUS
    - MagazinePistolUSP9
    - MagazinePistolUSP9
    - Whistle
    - Tourniquet
    - Zipties
