- type: job
  id: VDVMedic
  name: job-name-vdv-medic
  description: job-description-vdv-medic
  playTimeTracker: JobVDVMedic
  weight: 75
  startingGear: VDVMedicGear
  alwaysUseSpawner: true
  icon: "JobIconPACTMedic"
  requireAdminNotify: false
  supervisors: job-supervisors-rugov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
    - Ukrainian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - VDV
    - type: ChatRank
      rank: BF-rank-corporal
    - type: SurgerySpeedModifier
      SpeedModifier: 1.65
  - !type:AddImplantSpecial
    implants: [ TrackingImplantPACTRU ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - Medical
  - PACTCommon
  - PACTMaintenance
  - PACTMedical
  - PACTSoldier
  - PACTArmory

- type: startingGear
  id: VDVMedicGear
  equipment:
    id: VDVMedicPDA
    ears: ClothingHeadsetAltRU
    belt: ClothingBeltMedicalEMTFilledBF14 # ClothingBeltMilitaryWebbingRUFilledVityaz
    jumpsuit: ClothingUniformJumpsuitCamoRUEMR
    head: ClothingHeadHatHelmetRUEMR
    eyes: ClothingEyesHudMedicalBF
    outerClothing: ClothingOuterArmorPlateCarrierBlack
    shoes: ClothingShoesBootsJackFilledRU
    gloves: ClothingHandsGlovesLatex
#    back: ClothingBackpackRucksackBlack
    neck: ClothingNeckIFFtapeWhite
    suitstorage: WeaponRifleRUAKS74U
    pocket1: PouchMagsLargeFilledAK74
    pocket2: PouchGrenadesFilledVDVScout
  inhand:
    - PaperWrittenManualCombatMedic
  storage:
    back:
    - SupplyBoxMedicalFilled
    - DefibrillatorCompactBF
    - FlashlightMilitaryAlt
    - ClothingMaskGasRussiaPMK4
    - Tourniquet
    - Zipties
    - BF14AutoInjectorStormZCapped
