- type: job
  id: VDVRecon
  name: job-name-vdv-recon
  description: job-description-vdv-recon
  playTimeTracker: JobVDVRecon
  weight: 74
  startingGear: VDVReconGear
  alwaysUseSpawner: true
  icon: "JobIconPACTRecon"
  requireAdminNotify: false
  supervisors: job-supervisors-rugov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
    - Ukrainian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - VDV
    - type: ChatRank
      rank: BF-rank-corporal
  - !type:AddImplantSpecial
    implants: [ TrackingImplantPACTRU ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - PACTCommon
  - PACTMaintenance
  - PACTSoldier
  - PACTArmory

- type: startingGear
  id: VDVReconGear
  equipment:
    id: VDVReconPDA
    ears: ClothingHeadsetAltRU
    belt: ClothingBeltMilitaryWebbingRUFilledASVALShort
    jumpsuit: ClothingUniformJumpsuitCamoRUEMR
    head: ClothingHeadHatHelmetRUEMR
    helmetattachment: ClothingHelmetAttachmentNVGsBasicPACT
#    eyes: ClothingEyesGogglesGreen
    outerClothing: ClothingOuterArmorPlateCarrierBlack
    shoes: ClothingShoesBootsJackFilledRU
    back: ClothingBackpackRucksackBlack
    neck: ClothingNeckIFFtapeWhite
    suitstorage: WeaponRifleRUASVAL
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledVDVScout
  storage:
    back:
    - FlashlightMilitaryAlt
    - ClothingMaskGasRussiaPMK4
    - Rangefinder
    - Tourniquet
    - Zipties
